spring:

  batch:
    job:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      auto-index-creation: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: