spring:

  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  datasource:
    #    url: jdbc:h2:~/test
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
