spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/test?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring_2020_11.hw18.changelogs
