spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring_2020_11.hw13.changelogs